### ISSUE TITLE
Generation (interpolation) using epoch=5-step=30005.ckpt produces noise

### ISSUE THREAD

**Issue by haydensflee** [ixobert/birds-generation#11]
HI @ixobert I'm getting some strange results from running generation with the interpolation augmentation. The wav files I used are
pre-processed barnswallow bird songs from the kaggle dataset.

Here's the command I'm running
`python ./src/generate_samples.py  --data_paths="/opt/projects/birds-generation-master/interpolateThese/*.wav" --out_folder="/opt/projects/birds-generation-master/"  --model_path="/opt/projects/birds-generation-master/epoch=5-step=30005.ckpt"  --augmentations=interpolation --num_samples=3`

I just wanted to clarify what some of these arguments are expecting. Is data_paths a folder containing two .wav files that we wish to interpolate? And is num_samples the number of samples that we wish to generate from the two .wav files in data_paths?
Could you please try running generate_samples.py and tell me if that's how it's supposed to work? 

After the process finishes, I take the .npy files and I try to convert it back into a .wav file using the Griffin-Lim algorithm from librosa 0.10.0:

```
import librosa
import numpy as np
import soundfile as sf
from matplotlib import pyplot as plt
y=np.load("/opt/projects/birds-generation-master/interpolateThese/XC324851-0_interpolation0.99-XC324839.wav.wav.npy")
print(y)
S = np.abs(librosa.stft(y))

#plt.plot(S)
#plt.specgram(S)

inv = librosa.griffinlim(y)
istft=librosa.istft(y)


print(inv)
fig, ax = plt.subplots(nrows=3, sharex=True, sharey=True)
ax[0].set(title='Original', xlabel=None)
librosa.display.waveshow(inv,sr=22050,color='b', ax=ax[0])
plt.show()
sf.write("/home/hayden/interp1.wav", inv,22050)
```
The waveform looks and sounds like noise. Nothing like a chirp. Am I doing something wrong?

Edit: I used this same python script to convert the barnswallow bird song into a .npy spectrogram array and used Griffin-Lim to convert it back into a .wav file and it sounded good so the script is working well. I suspect something is going wrong with generation or I'm using the model incorrectly or something...

**Comment by ixobert** [comment]
@haydensflee, sorry for the late reply, was unvailable for a bit. 
Yeah I will be curious to see why you are not getting anything, can you try importing your file in the interactive script that I have shared https://github.com/ixobert/birds-generation/blob/master/src/interactive_app.py ?

**Comment by haydensflee** [comment]
@ixobert Thanks for that fix!
I was able to run the interpolation through interactive_app.py after modifying a few of the filepaths in the script so it seems to be working fine now :)
Also had to replace line 247 of interactive_app.py 
FROM col1, col2 = st.beta_columns(2) TO col1, col2 = st.columns(2)
since streamlit was released from beta in late 2021.

Cheers
