### ISSUE TITLE
Librosa TypeError: resample() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by sammlapp** [ixobert/birds-generation#9]
Maybe I have a different version of librosa than expected by the package, mine is `librosa 0.10.1`. It might be a good idea to use positional arguments in all calls to librosa.resample:

https://github.com/ixobert/birds-generation/blob/cd55a99e00c291fcbcb77cbbd0621b93afe9ce03/src/interactive_app.py#L117

https://github.com/ixobert/birds-generation/blob/cd55a99e00c291fcbcb77cbbd0621b93afe9ce03/src/generate_samples.py#L55

https://github.com/ixobert/birds-generation/blob/cd55a99e00c291fcbcb77cbbd0621b93afe9ce03/src/dataloaders/audiodataset.py#L185

https://github.com/ixobert/birds-generation/blob/cd55a99e00c291fcbcb77cbbd0621b93afe9ce03/src/train_classifier.py#L66

(would become `audio = librosa.resample(y=audio, orig_sr=_sr, target_sr=sr)`

**Comment by sammlapp** [comment]
the same applies to librosa.util.fix_length

**Comment by ixobert** [comment]
Thanks @sammlapp, I have updated the code accordingly.
